version: '3'
services:
  copyprotectionpioneers:
    build: .
    image: he2022/copyprotectionpioneers
    restart: always
    networks:
      - challengenet
    ports:
      - "2209:80"
networks:
  challengenet:
    external: true