version: '3'
services:
  ghostinashell3:
    build: .
    image: he2022/ghostinashell3
    restart: always
    networks:
      - challengenet
    ports:
      - "2203:22"
    environment:
      - SSH_USERS=pinky:1000:1000
      - SSH_ENABLE_PASSWORD_AUTH=true
    volumes:
      - keys:/etc/ssh/keys
volumes:
  keys:
networks:
  challengenet:
    external: true